#-----------------------------------------------------------------------------
#
#      File         :  Makefile
#      Abstract     :  Driver-specific makefile entries
#
#-----------------------------------------------------------------------------


#=============================================================================
# Set C_SRC to contain the list of files to compile
#=============================================================================
C_SRC =  \
    ApiFunc.c       \
    Dispatch.c      \
    Driver.c        \
    ModuleVersion.c \
    PciFunc.c       \
    PlxChipFn.c     \
    PlxInterrupt.c  \
    SuppFunc.c
