#-----------------------------------------------------------------------------
#
#      File         :  Makefile
#      Abstract     :  Driver-specific makefile entries
#
#-----------------------------------------------------------------------------


#=============================================================================
# Set C_SRC to contain the list of files to compile
#=============================================================================
C_SRC =  \
    ApiFunc.c       \
    ChipFunc.c      \
    Dispatch.c      \
    Driver.c        \
    Eep_6000.c      \
    Eep_8000.c      \
    Eep_8111.c      \
    ModuleVersion.c \
    PciFunc.c       \
    SuppFunc.c
